#!/bin/bash

# .env ファイルを .env.localからコピーして生成する
if [ ! -e '.env' ]; then
    echo envファイルを生成します。
    cp .env.local .env
    echo envファイルが生成されました。
fi

# localのループバックIPを一つ設定する
LOCAL_IP=$(grep LOCAL_IP .env | cut -d '=' -f2)

# macにて必要に応じて sudo ifconfig lo0 alias を叩く
if ifconfig | grep -i "$LOCAL_IP"  >/dev/null; then
    echo "$LOCAL_IP" は有効です。
else
    echo "$LOCAL_IP" が無効なのでエイリアスを生成します。パスワードを入力してください。
    sudo ifconfig lo0 alias "$LOCAL_IP" up
fi

# プロジェクト名定義
COMPOSE_PROJECT_NAME=$(grep PROJECT_DOMAIN .env | cut -d '=' -f2 | head -1)

# コンテナ名サフィックス
HTTPS_SUFFIX=$(grep HTTPS_SUFFIX .env | cut -d '=' -f2 | head -1)
WEB_SUFFIX=$(grep WEB_SUFFIX .env | cut -d '=' -f2 | head -1)
APP_SUFFIX=$(grep APP_SUFFIX .env | cut -d '=' -f2 | head -1)
DB_SUFFIX=$(grep DB_SUFFIX .env | cut -d '=' -f2 | head -1)

# コンテナ名定義
HTTPS="${COMPOSE_PROJECT_NAME}${HTTPS_SUFFIX}"
WEB="${COMPOSE_PROJECT_NAME}${WEB_SUFFIX}"
APP="${COMPOSE_PROJECT_NAME}${APP_SUFFIX}"
DB="${COMPOSE_PROJECT_NAME}${DB_SUFFIX}"

# サービス名定義
SCHEMA_SERVICE="schemaspy"

# コマンド定義
RUN_APP="docker exec -it ${APP}"

# コンテナ内のパス定義
REMOTE_APP_DIR="/opt/${COMPOSE_PROJECT_NAME}"
REMOTE_VENDOR_DIR="${REMOTE_APP_DIR}/vendor"
REMOTE_NODE_DIR="${REMOTE_APP_DIR}/node_modules"

# ローカルのパス定義
LOCAL_APP_DIR="../../src"
LOCAL_VENDOR_DIR="${LOCAL_APP_DIR}/vendor"
LOCAL_NODE_DIR="${LOCAL_APP_DIR}/node_modules"

case "$1" in

"create")
# イメージ、データボリュームの全消し。最初からやり直す場合に使用する。
  docker-compose down --rmi all --volumes --remove-orphans
  rm -rf ${LOCAL_VENDOR_DIR}
  rm -rf ${LOCAL_NODE_DIR}

  docker-compose up -d --build

  ${RUN_APP} dockerize -timeout 60s -wait tcp://"${DB}":5432

  ${RUN_APP} chmod 777 -R storage
  ${RUN_APP} composer install
  ${RUN_APP} composer dump-autoload

  ${RUN_APP} ./artisan migrate:refresh --seed

  ${RUN_APP} ./artisan ide-helper:generate
  ${RUN_APP} ./artisan ide-helper:models --nowrite

  ${RUN_APP} yarn install
  ${RUN_APP} yarn run dev

  docker cp "${APP}":"${REMOTE_VENDOR_DIR}" ${LOCAL_APP_DIR}
  docker cp "${APP}":"${REMOTE_NODE_DIR}" ${LOCAL_APP_DIR}

  docker cp "${APP}":"${REMOTE_APP_DIR}"/_ide_helper.php ${LOCAL_APP_DIR}
  docker cp "${APP}":"${REMOTE_APP_DIR}"/_ide_helper_models.php ${LOCAL_APP_DIR}

  docker-compose run --rm ${SCHEMA_SERVICE}

  docker container prune -f
  docker image prune -f
  docker images
  docker ps -a
  ;;

"rebuild")
# イメージだけリビルドする
  docker-compose down
  docker-compose up -d --build
  docker container prune -f
  docker image prune -f
  docker images
  docker ps -a
  ;;

"setup")
# ボリュームを削除して再度やり直す
  docker-compose down --volumes --remove-orphans

  rm -rf ${LOCAL_VENDOR_DIR}
  rm -rf ${LOCAL_NODE_DIR}

  docker-compose up -d

  ${RUN_APP} chmod 777 -R storage
  ${RUN_APP} composer install
  ${RUN_APP} composer dump-autoload

  ${RUN_APP} ./artisan migrate:refresh --seed


  ${RUN_APP} ./artisan ide-helper:generate
  ${RUN_APP} ./artisan ide-helper:models --nowrite

  ${RUN_APP} yarn install
  ${RUN_APP} yarn run dev

  docker cp ${APP}:${REMOTE_VENDOR_DIR} ${LOCAL_APP_DIR}
  docker cp ${APP}:${REMOTE_NODE_DIR} ${LOCAL_APP_DIR}

  docker cp ${APP}:${REMOTE_APP_DIR}/_ide_helper.php ${LOCAL_APP_DIR}
  docker cp ${APP}:${REMOTE_APP_DIR}/_ide_helper_models.php ${LOCAL_APP_DIR}

  docker-compose run --rm ${SCHEMA_SERVICE}

  docker container prune -f
  docker image prune -f
  docker images
  docker ps -a
  ;;

"up")
# docker-composeの単純な再起動
  docker-compose down
  docker-compose up -d
  docker ps -a
  ;;

"down")
# docker-compose down
  docker-compose down
  docker container prune -f
  docker image prune -f
  docker images
  docker ps -a
  ;;

"https")
  docker exec -it "${HTTPS}" bash
  ;;

"web")
  docker exec -it "${WEB}" sh
  ;;

"app")
  docker exec -it ${APP} sh
  ;;

"schema")
  docker-compose run --rm ${SCHEMA_SERVICE}
  ;;

"ide")
  ${RUN_APP} ./artisan ide-helper:generate
  ${RUN_APP} ./artisan ide-helper:models --nowrite
  docker cp "${APP}":"${REMOTE_APP_DIR}"/_ide_helper.php ${LOCAL_APP_DIR}
  docker cp "${APP}":"${REMOTE_APP_DIR}"/_ide_helper_models.php ${LOCAL_APP_DIR}
  ;;

"db:refresh")
  ${RUN_APP} ./artisan migrate:refresh --seed
  ;;

"composer")
  rm -rf ${LOCAL_VENDOR_DIR}
  ${RUN_APP} composer "${@:2}"
  docker cp ${APP}:${REMOTE_VENDOR_DIR} ${LOCAL_APP_DIR}
  ;;

"artisan")
  ${RUN_APP} ./artisan "${@:2}"
  ;;

"yarn")
  rm -rf ${LOCAL_NODE_DIR}
  ${RUN_APP} yarn "${@:2}"
  docker cp ${APP}:${REMOTE_NODE_DIR} ${LOCAL_APP_DIR}
  ;;

"watch")
  ${RUN_APP} yarn run watch-poll
  ;;

"logs")
  docker-compose logs -f
  ;;

"test")
  docker exec -i ${APP} ./vendor/bin/phpunit
  ;;
esac
